spring:
  profiles:
    active: dev  # 기본적으로 "dev" 설정 사용

---
spring:
  config:
    activate:
      on-profile: dev  # 개발 환경 설정
  datasource:
    url: jdbc:mysql://localhost:3306/moaram
    username: root
    password: password
  jpa:
    show-sql: true
    open-in-view: false

---
spring:
  config:
    activate:
      on-profile: prod  # 운영 환경 설정
  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    open-in-view: false

---
app:
  allowed-urls:
    - "/"
    - "/public/**"
    - "/swagger-ui/**"
    - "/v3/api-docs/**"
